<<: &shared
  language_name: Kwak'wala
mappings:
  - display_name: Kwak'wala IPA to English IPA
    rules_path: kwk_ipa_to_eng_ipa.json
    in_lang: kwk-ipa
    out_lang: eng-ipa
    case_sensitive: false
    authors:
      - Patrick Littell
    <<: *shared
  - display_name: Kwak'wala (NAPA) to IPA
    rules_path: kwk_napa_to_ipa.csv
    in_lang: kwk-napa
    out_lang: kwk-ipa
    rule_ordering: apply-longest-first
    authors:
      - Patrick Littell
      - Fineen Davis
    language_name: Kwak'wala (NAPA orthography)
  - display_name: Kwak'wala (U'mista) to IPA
    rules_path: kwk_umista_to_ipa.json
    in_lang: kwk-umista
    out_lang: kwk-ipa
    rule_ordering: apply-longest-first
    authors:
      - Patrick Littell
    <<: *shared
  - display_name: Kwak'wala (U'mista) Equivalencies
    rules_path: umista_equiv.csv
    in_lang: kwk-umista
    out_lang: kwk-umista-con
    rule_ordering: apply-longest-first
    authors:
      - Fineen Davis
    language_name: Kwak'wala (U'mista orthography)
  - display_name: Kwak'wala (NAPA) Equivalencies
    rules_path: napa_equiv_ubc.csv
    in_lang: kwk-napa-ubc
    out_lang: kwk-napa-ubc-con
    rule_ordering: apply-longest-first
    authors:
      - Fineen Davis
    <<: *shared
  - display_name: Kwak'wala (NAPA) Equivalencies
    rules_path: napa_equiv_uvic.csv
    in_lang: kwk-napa-uvic
    out_lang: kwk-napa-uvic-con
    rule_ordering: apply-longest-first
    authors:
      - Fineen Davis
    <<: *shared
  - display_name: Kwak'wala (Boas) to Umista
    rules_path: kwk_boas_to_umista.csv
    in_lang: kwk-boas
    out_lang: kwk-umista
    rule_ordering: apply-longest-first
    prevent_feeding: true
    case_sensitive: false
    preserve_case: true
    authors:
      - Fineen Davis
      - Olivia Chen
      - Daisy Rosenblum
      - Dante cerron
    language_name: Kwak'wala (Boas orthography)
