<<: &shared
  language_name: East Cree, Northern
mappings:
  - display_name: Northern East Cree Equivalencies
    in_lang: crl
    out_lang: crl-equiv
    type: mapping
    authors:
      - Delasie Torkornoo
      - Aidan Pine
      - Eric Joanis
    rules_path: crl_equiv.json
    rule_ordering: as-written
    case_sensitive: false
    <<: *shared
  - display_name: Northern East Cree to IPA
    in_lang: crl-equiv
    out_lang: crl-ipa
    type: mapping
    authors:
      - David Huggins-Daines
      - Patrick Littell
      - Delasie Torkornoo
    rules_path: crl_to_ipa.json
    rule_ordering: apply-longest-first
    case_sensitive: false
    <<: *shared
  - display_name: Northern East Cree IPA to English IPA
    in_lang: crl-ipa
    out_lang: eng-ipa
    type: mapping
    rules_path: crl_ipa_to_eng_ipa.json
    rule_ordering: apply-longest-first
    case_sensitive: false
    <<: *shared
