<<: &shared
  language_name: Yiddish
mappings:
  - display_name: Yiddish to IPA
    in_lang: yid
    out_lang: yid-ipa
    abbreviations_path: abbreviations.csv
    authors:
      - Aidan Pine
      - Hannah Pandher
    type: mapping
    rules_path: yid_to_ipa.csv
    prevent_feeding: false
    rule_ordering: as-written
    case_sensitive: false
    norm_form: NFD
    <<: *shared
